import {createHash, createHmac, randomBytes, randomInt, randomUUID, timingSafeEqual} from 'node:crypto';
import {HttpError} from './providers.mjs';
import {attachmentImageIds} from './community-attachments.mjs';

const now=()=>new Date().toISOString();
const missing=()=>new HttpError(404,'群聊不存在或你已不在群内。');
const invalidCursor=()=>new HttpError(400,'群聊分页游标无效或与当前账号、群聊、入群记录不匹配。');
const limitValue=(params,fallback=20)=>{const value=params.get('limit'),limit=value===null?fallback:Number(value);if(!Number.isSafeInteger(limit)||limit<1||limit>50)throw new HttpError(400,'每页数量应为 1–50。');return limit;};
const text=(value,maximum,label,required=false)=>{if(typeof value!=='string'||value.includes('\0')||Array.from(value).length>maximum||(required&&!value.trim()))throw new HttpError(400,`${label}${required?'不能为空，且':''}最多 ${maximum} 字。`);return value.trim();};
const mutationId=(value,required=true)=>{if(value===undefined&&!required)return null;if(typeof value!=='string'||!/^[\w:-]{1,100}$/.test(value))throw new HttpError(400,'请提供有效的请求唯一键 clientMutationId。');return value;};
const bool=(value,label)=>{if(typeof value!=='boolean')throw new HttpError(400,`${label}应为 true 或 false。`);return value;};

/** All group writes recheck the current member after an awaited request body. */
export function createCommunityGroups({db,author,transactionFor,throttle,readBody,send,media}) {
  db.prepare('INSERT OR IGNORE INTO community_group_settings(key,value) VALUES(?,?)').run('cursor-secret',randomBytes(32).toString('hex'));
  const secret=db.prepare('SELECT value FROM community_group_settings WHERE key=?').get('cursor-secret').value;
  function encode(value){const data=Buffer.from(JSON.stringify(value)).toString('base64url'),mac=createHmac('sha256',secret).update(data).digest('base64url');return `${data}.${mac}`;}
  function decode(value){try{const [data,mac,...extra]=String(value).split('.'),expected=createHmac('sha256',secret).update(data).digest(),given=Buffer.from(mac,'base64url');if(extra.length||given.length!==expected.length||!timingSafeEqual(given,expected))throw invalidCursor();return JSON.parse(Buffer.from(data,'base64url').toString('utf8'));}catch{throw invalidCursor();}}
  function groupRow(id){const row=db.prepare("SELECT * FROM community_groups WHERE id=? AND status='active'").get(id);if(!row)throw missing();return row;}
  function memberRow(id,userId){groupRow(id);const member=db.prepare('SELECT * FROM community_group_members WHERE group_id=? AND user_id=?').get(id,userId);if(!member)throw missing();return member;}
  const canManage=member=>member.role==='owner'||member.role==='admin';
  function manager(id,userId,ownerOnly=false){const member=memberRow(id,userId);if(ownerOnly?member.role!=='owner':!canManage(member))throw new HttpError(403,ownerOnly?'仅群主可以执行此操作。':'仅群主或管理员可以执行此操作。');return member;}
  function memberCount(id){return db.prepare('SELECT COUNT(*) AS count FROM community_group_members WHERE group_id=?').get(id).count;}
  function messageDto(row,userId){const mentions=JSON.parse(row.mention_user_ids);return {id:row.id,groupId:row.group_id,senderId:row.sender_id,sender:author(row.sender_id,userId),body:row.body,images:media?.attachmentImages('group-message',row.id)||[],clientMutationId:row.client_mutation_id,sequence:row.seq,createdAt:row.created_at,mentionUserIds:mentions,mentionUsers:mentions.map(id=>author(id,userId)),mentionAll:Boolean(row.mention_all),mentionedMe:row.sender_id!==userId&&(Boolean(row.mention_all)||mentions.includes(userId))};}
  function unreadCount(userId,groupId=null,mentionsOnly=false){return db.prepare(`SELECT COUNT(*) AS count FROM community_group_messages m JOIN community_group_members p ON p.group_id=m.group_id AND p.user_id=? JOIN community_groups g ON g.id=m.group_id AND g.status='active' WHERE m.sender_id<>? AND m.seq>p.joined_seq AND m.seq>p.last_read_seq ${groupId?'AND m.group_id=?':''} ${mentionsOnly?'AND (m.mention_all=1 OR EXISTS(SELECT 1 FROM json_each(m.mention_user_ids) WHERE value=?))':''}`).get(userId,userId,...(groupId?[groupId]:[]),...(mentionsOnly?[userId]:[])).count;}
  const mentionUnreadCount=(userId,groupId=null)=>unreadCount(userId,groupId,true);
  const invitationCount=userId=>db.prepare("SELECT COUNT(*) AS count FROM community_group_invitations i JOIN community_groups g ON g.id=i.group_id AND g.status='active' WHERE i.user_id=? AND i.status='pending' AND NOT EXISTS(SELECT 1 FROM community_group_members p WHERE p.group_id=i.group_id AND p.user_id=i.user_id)").get(userId).count;
  const totals=userId=>({unreadCount:unreadCount(userId),mentionUnreadCount:mentionUnreadCount(userId),invitationCount:invitationCount(userId)});
  function publicDto(row){return {id:row.id,groupNumber:row.group_number,name:row.name,description:row.description,memberCount:memberCount(row.id),createdAt:row.created_at};}
  function groupDto(row,userId){const member=memberRow(row.id,userId),last=db.prepare('SELECT * FROM community_group_messages WHERE group_id=? AND seq>? ORDER BY seq DESC LIMIT 1').get(row.id,member.joined_seq);return {...publicDto(row),announcement:row.announcement,ownerId:row.owner_id,role:member.role,muted:Boolean(member.muted),muteAll:Boolean(row.mute_all),status:row.status,lastMessage:last?messageDto(last,userId):null,unreadCount:unreadCount(userId,row.id),mentionUnreadCount:mentionUnreadCount(userId,row.id),updatedAt:row.updated_at,canManage:canManage(member),canSend:!member.muted&&(!row.mute_all||member.role!=='member')};}
  const memberDto=(row,userId)=>({...author(row.user_id,userId),role:row.role,muted:Boolean(row.muted),joinedAt:row.joined_at});
  const requestDto=(row,userId)=>({id:row.id,user:author(row.user_id,userId),status:row.status,createdAt:row.created_at});
  function invitationDto(row,userId){const group=db.prepare('SELECT * FROM community_groups WHERE id=?').get(row.group_id);return {id:row.id,group:group?{id:group.id,groupNumber:group.group_number,name:group.name,memberCount:memberCount(group.id)}:null,inviter:author(row.inviter_id,userId),status:row.status,createdAt:row.created_at};}
  function listCursor(params,scope,userId,membership=null){if(!params.has('cursor'))return null;const cursor=decode(params.get('cursor'));if(cursor.scope!==scope||cursor.userId!==userId||cursor.membershipId!==(membership?.id??null)||typeof cursor.id!=='string'||typeof cursor.order!=='string')throw invalidCursor();return cursor;}
  function page(rows,limit,dto,scope,userId,membership=null,order=row=>row.created_at){const hasMore=rows.length>limit,selected=rows.slice(0,limit),last=selected.at(-1);return {items:selected.map(dto),hasMore,nextCursor:hasMore?encode({scope,userId,membershipId:membership?.id??null,id:last.id,order:String(order(last))}):null};}
  function joinMember(group,userId){const existing=db.prepare('SELECT * FROM community_group_members WHERE group_id=? AND user_id=?').get(group.id,userId);if(existing)return existing;if(!db.prepare('SELECT 1 FROM users WHERE id=?').get(userId))throw new HttpError(404,'社区用户不存在。');if(memberCount(group.id)>=100)throw new HttpError(409,'群成员已达到 100 人上限。');const id=randomUUID(),time=now();db.prepare('INSERT INTO community_group_members(id,group_id,user_id,joined_seq,last_read_seq,delivered_seq,joined_at) VALUES(?,?,?,?,?,?,?)').run(id,group.id,userId,group.last_seq,group.last_seq,group.last_seq,time);db.prepare("UPDATE community_group_requests SET status='cancelled',updated_at=? WHERE group_id=? AND user_id=? AND status='pending'").run(time,group.id,userId);db.prepare("UPDATE community_group_invitations SET status='revoked',updated_at=? WHERE group_id=? AND user_id=? AND status='pending'").run(time,group.id,userId);return memberRow(group.id,userId);}
  function removeMember(id,userId){db.prepare('DELETE FROM community_group_members WHERE group_id=? AND user_id=?').run(id,userId);db.prepare("UPDATE community_group_invitations SET status='revoked',updated_at=? WHERE group_id=? AND status='pending' AND (user_id=? OR inviter_id=?)").run(now(),id,userId,userId);db.prepare("UPDATE community_group_requests SET status='cancelled',updated_at=? WHERE group_id=? AND user_id=? AND status='pending'").run(now(),id,userId);}
  function dissolve(id){const time=now();db.prepare("UPDATE community_groups SET status='dissolved',updated_at=? WHERE id=?").run(time,id);db.prepare('DELETE FROM community_group_members WHERE group_id=?').run(id);db.prepare("UPDATE community_group_invitations SET status='revoked',updated_at=? WHERE group_id=? AND status='pending'").run(time,id);db.prepare("UPDATE community_group_requests SET status='cancelled',updated_at=? WHERE group_id=? AND status='pending'").run(time,id);}
  function messageCursor(value,group,member,userId,forward){if(forward&&value==='0')return member.joined_seq;const message=db.prepare('SELECT seq FROM community_group_messages WHERE id=? AND group_id=? AND seq>?').get(value,group.id,member.joined_seq);if(message)return message.seq;const cursor=decode(value);if(cursor.kind!=='group-messages'||cursor.userId!==userId||cursor.groupId!==group.id||cursor.membershipId!==member.id||cursor.joinedSeq!==member.joined_seq||!Number.isSafeInteger(cursor.seq)||cursor.seq<=member.joined_seq||!db.prepare('SELECT 1 FROM community_group_messages WHERE group_id=? AND seq=?').get(group.id,cursor.seq))throw invalidCursor();return cursor.seq;}
  const cursorFor=(row,group,member,userId)=>encode({kind:'group-messages',userId,groupId:group.id,membershipId:member.id,joinedSeq:member.joined_seq,seq:row.seq});

  async function handle(req,res,user,path,params=new URLSearchParams()) {
    if(!path.startsWith('/groups'))return false;
    const reply=(status,body)=>{send(res,status,body);return true;};
    if(path==='/groups/unread'&&req.method==='GET')return reply(200,totals(user.id));
    if(path==='/groups/search'&&req.method==='GET'){const q=params.get('q')||'';if(!/^[1-9]\d{7}$/.test(q))throw new HttpError(400,'请填写完整的 8 位群号。');const group=db.prepare("SELECT * FROM community_groups WHERE group_number=? AND status='active'").get(q);return reply(200,{items:group?[publicDto(group)]:[],hasMore:false,nextCursor:null});}
    if(path==='/groups'&&req.method==='GET'){
      const limit=limitValue(params),scope='groups',cursor=listCursor(params,scope,user.id);
      if(cursor&&!/^\d+$/.test(cursor.order))throw invalidCursor();
      const rows=db.prepare(`SELECT g.* FROM community_groups g JOIN community_group_members p ON p.group_id=g.id AND p.user_id=? WHERE g.status='active' ${cursor?'AND (g.last_seq<? OR (g.last_seq=? AND g.id<?))':''} ORDER BY g.last_seq DESC,g.id DESC LIMIT ?`).all(user.id,...(cursor?[Number(cursor.order),Number(cursor.order),cursor.id]:[]),limit+1);
      return reply(200,{...page(rows,limit,row=>groupDto(row,user.id),scope,user.id,null,row=>row.last_seq),...totals(user.id)});
    }
    if(path==='/groups'&&req.method==='POST'){
      const body=await readBody(req,8000),name=text(body.name,30,'群名称',true),description=text(body.description??'',120,'群简介'),announcement=text(body.announcement??'',500,'群公告'),mutation=mutationId(body.clientMutationId,false),hash=createHash('sha256').update(JSON.stringify({name,description,announcement})).digest('hex');
      const result=transactionFor(user,()=>{if(mutation){const receipt=db.prepare('SELECT * FROM community_group_mutations WHERE user_id=? AND mutation_id=?').get(user.id,mutation);if(receipt){if(receipt.request_hash!==hash)throw new HttpError(409,'此请求唯一键已用于其他建群内容。');return {group:groupDto(groupRow(receipt.group_id),user.id)};}}
        throttle(user.id,'group-create',20,60*60*1000);const id=randomUUID(),time=now();let number;do{number=String(randomInt(10000000,100000000));}while(db.prepare('SELECT 1 FROM community_groups WHERE group_number=?').get(number));db.prepare('INSERT INTO community_groups(id,group_number,owner_id,name,description,announcement,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(id,number,user.id,name,description,announcement,time,time);db.prepare("INSERT INTO community_group_members(id,group_id,user_id,role,joined_at) VALUES(?,?,?,'owner',?)").run(randomUUID(),id,user.id,time);if(mutation)db.prepare('INSERT INTO community_group_mutations(user_id,mutation_id,request_hash,group_id) VALUES(?,?,?,?)').run(user.id,mutation,hash,id);return {group:groupDto(groupRow(id),user.id)};});return reply(201,result);
    }
    if(path==='/groups/invitations'&&req.method==='GET'){
      const limit=limitValue(params),scope='group-invitations',cursor=listCursor(params,scope,user.id),rows=db.prepare(`SELECT i.* FROM community_group_invitations i JOIN community_groups g ON g.id=i.group_id AND g.status='active' WHERE i.user_id=? AND i.status='pending' AND NOT EXISTS(SELECT 1 FROM community_group_members p WHERE p.group_id=i.group_id AND p.user_id=i.user_id) ${cursor?'AND (i.created_at<? OR (i.created_at=? AND i.id<?))':''} ORDER BY i.created_at DESC,i.id DESC LIMIT ?`).all(user.id,...(cursor?[cursor.order,cursor.order,cursor.id]:[]),limit+1);return reply(200,page(rows,limit,row=>invitationDto(row,user.id),scope,user.id));
    }
    let match=path.match(/^\/groups\/invitations\/([^/]+)$/);
    if(match&&req.method==='PATCH'){
      const body=await readBody(req,2000);if(!['accept','decline'].includes(body.action))throw new HttpError(400,'请选择接受或拒绝邀请。');
      const result=transactionFor(user,()=>{const invitation=db.prepare('SELECT * FROM community_group_invitations WHERE id=? AND user_id=?').get(match[1],user.id);if(!invitation)throw new HttpError(404,'群邀请不存在或无权处理。');const group=groupRow(invitation.group_id);if(invitation.status!=='pending'){const membership=db.prepare('SELECT id FROM community_group_members WHERE group_id=? AND user_id=?').get(group.id,user.id);if(invitation.status==='accepted'&&body.action==='accept'&&membership?.id===invitation.membership_id)return {invitation:invitationDto(invitation,user.id),group:groupDto(group,user.id)};if(invitation.status==='declined'&&body.action==='decline')return {invitation:invitationDto(invitation,user.id)};throw new HttpError(409,'此邀请已处理或已失效。');}memberRow(group.id,invitation.inviter_id);if(body.action==='decline'){db.prepare("UPDATE community_group_invitations SET status='declined',updated_at=? WHERE id=?").run(now(),invitation.id);return {invitation:invitationDto(db.prepare('SELECT * FROM community_group_invitations WHERE id=?').get(invitation.id),user.id)};}const member=joinMember(group,user.id);db.prepare("UPDATE community_group_invitations SET status='accepted',membership_id=?,updated_at=? WHERE id=?").run(member.id,now(),invitation.id);return {invitation:invitationDto(db.prepare('SELECT * FROM community_group_invitations WHERE id=?').get(invitation.id),user.id),group:groupDto(group,user.id)};});return reply(200,result);
    }
    match=path.match(/^\/groups\/([^/]+)(?:\/(members|messages|read|join|requests|invitations|leave|transfer)(?:\/([^/]+))?)?$/);
    if(!match)throw new HttpError(404,'群聊接口不存在。');const id=match[1],action=match[2],target=match[3];
    if(!action&&req.method==='GET')return reply(200,{group:groupDto(groupRow(id),user.id)});
    if(!action&&req.method==='PATCH'){
      manager(id,user.id);const body=await readBody(req,8000),changes={};for(const [field,max,label]of [['name',30,'群名称'],['description',120,'群简介'],['announcement',500,'群公告']])if(Object.hasOwn(body,field))changes[field]=text(body[field],max,label,field==='name');if(Object.hasOwn(body,'muteAll'))changes.mute_all=bool(body.muteAll,'全员禁言')?1:0;if(!Object.keys(changes).length)throw new HttpError(400,'请提供要修改的群资料。');const result=transactionFor(user,()=>{manager(id,user.id);db.prepare(`UPDATE community_groups SET ${Object.keys(changes).map(key=>`${key}=?`).join(',')},updated_at=? WHERE id=?`).run(...Object.values(changes),now(),id);return {group:groupDto(groupRow(id),user.id)};});return reply(200,result);
    }
    if(!action&&req.method==='DELETE'){manager(id,user.id,true);await readBody(req,2000);const result=transactionFor(user,()=>{manager(id,user.id,true);dissolve(id);return {ok:true};});await media?.cleanupExpired();return reply(200,result);}
    if(action==='join'&&!target&&req.method==='POST'){
      groupRow(id);await readBody(req,2000);const result=transactionFor(user,()=>{const group=groupRow(id),member=db.prepare('SELECT * FROM community_group_members WHERE group_id=? AND user_id=?').get(id,user.id);if(member)return {status:'member',request:null,group:groupDto(group,user.id)};let request=db.prepare("SELECT * FROM community_group_requests WHERE group_id=? AND user_id=? AND status='pending'").get(id,user.id);if(!request){throttle(user.id,'group-join',30,60*60*1000);const requestId=randomUUID(),time=now();db.prepare('INSERT INTO community_group_requests(id,group_id,user_id,created_at,updated_at) VALUES(?,?,?,?,?)').run(requestId,id,user.id,time,time);request=db.prepare('SELECT * FROM community_group_requests WHERE id=?').get(requestId);}return {status:'pending',request:requestDto(request,user.id)};});return reply(200,result);
    }
    const member=memberRow(id,user.id),group=groupRow(id);
    if(action==='members'&&!target&&req.method==='GET'){
      const limit=limitValue(params),scope='group-members:'+id,cursor=listCursor(params,scope,user.id,member),rows=db.prepare(`SELECT *,user_id AS cursor_user FROM community_group_members WHERE group_id=? ${cursor?'AND (joined_at>? OR (joined_at=? AND user_id>?))':''} ORDER BY joined_at,user_id LIMIT ?`).all(id,...(cursor?[cursor.order,cursor.order,cursor.id]:[]),limit+1);return reply(200,page(rows.map(row=>({...row,id:row.user_id})),limit,row=>memberDto(row,user.id),scope,user.id,member,row=>row.joined_at));
    }
    if(action==='members'&&target&&(req.method==='PATCH'||req.method==='DELETE')){
      manager(id,user.id);const body=await readBody(req,2000),remove=req.method==='DELETE';if(!remove&&!Object.hasOwn(body,'role')&&!Object.hasOwn(body,'muted'))throw new HttpError(400,'请选择成员角色或禁言状态。');if(Object.hasOwn(body,'role')&&!['admin','member'].includes(body.role))throw new HttpError(400,'成员角色只能为管理员或普通成员。');if(Object.hasOwn(body,'muted'))bool(body.muted,'个人禁言');
      const result=transactionFor(user,()=>{const actor=manager(id,user.id),recipient=memberRow(id,target);if(recipient.role==='owner')throw new HttpError(403,'不能修改或移除群主，请使用群主转让。');if(actor.role!=='owner'&&(recipient.role!=='member'||Object.hasOwn(body,'role')))throw new HttpError(403,'仅群主可以任免管理员；管理员不能修改其他管理员。');if(remove){removeMember(id,target);return {ok:true};}db.prepare('UPDATE community_group_members SET role=?,muted=? WHERE group_id=? AND user_id=?').run(body.role??recipient.role,Object.hasOwn(body,'muted')?Number(body.muted):recipient.muted,id,target);return {member:memberDto(memberRow(id,target),user.id)};});return reply(200,result);
    }
    if(action==='requests'&&!target&&req.method==='GET'){
      manager(id,user.id);const limit=limitValue(params),status=params.get('status')||'pending';if(!['pending','approved','rejected','cancelled','all'].includes(status))throw new HttpError(400,'申请状态无效。');const scope='group-requests:'+id+':'+status,cursor=listCursor(params,scope,user.id,member),rows=db.prepare(`SELECT * FROM community_group_requests WHERE group_id=? ${status==='all'?'':'AND status=?'} ${cursor?'AND (created_at<? OR (created_at=? AND id<?))':''} ORDER BY created_at DESC,id DESC LIMIT ?`).all(id,...(status==='all'?[]:[status]),...(cursor?[cursor.order,cursor.order,cursor.id]:[]),limit+1);return reply(200,page(rows,limit,row=>requestDto(row,user.id),scope,user.id,member));
    }
    if(action==='requests'&&target&&req.method==='PATCH'){
      manager(id,user.id);const body=await readBody(req,2000);if(!['approve','reject'].includes(body.action))throw new HttpError(400,'请选择批准或拒绝申请。');const result=transactionFor(user,()=>{manager(id,user.id);const currentGroup=groupRow(id),request=db.prepare('SELECT * FROM community_group_requests WHERE id=? AND group_id=?').get(target,id);if(!request)throw new HttpError(404,'入群申请不存在。');if(request.status!=='pending'){const current=db.prepare('SELECT id FROM community_group_members WHERE group_id=? AND user_id=?').get(id,request.user_id);if(request.status==='approved'&&body.action==='approve'&&current?.id===request.membership_id||request.status==='rejected'&&body.action==='reject')return {request:requestDto(request,user.id)};throw new HttpError(409,'此申请已处理或已失效。');}let admission=null;if(body.action==='approve')admission=joinMember(currentGroup,request.user_id);db.prepare('UPDATE community_group_requests SET status=?,membership_id=?,updated_at=? WHERE id=?').run(body.action==='approve'?'approved':'rejected',admission?.id??null,now(),target);return {request:requestDto(db.prepare('SELECT * FROM community_group_requests WHERE id=?').get(target),user.id)};});return reply(200,result);
    }
    if(action==='invitations'&&!target&&req.method==='POST'){
      const body=await readBody(req,6000);if(!Array.isArray(body.userIds)||!body.userIds.length||body.userIds.length>20||body.userIds.some(value=>typeof value!=='string'||!value||value.length>100))throw new HttpError(400,'每次请选择 1–20 位社区用户。');const userIds=[...new Set(body.userIds)];const result=transactionFor(user,()=>{memberRow(id,user.id);for(const userId of userIds){if(!db.prepare('SELECT 1 FROM users WHERE id=?').get(userId))throw new HttpError(404,'社区用户不存在。');if(db.prepare('SELECT 1 FROM community_group_members WHERE group_id=? AND user_id=?').get(id,userId))throw new HttpError(400,'所选用户已是群成员。');}throttle(user.id,'group-invite',60,60*60*1000);const items=userIds.map(userId=>{let invitation=db.prepare("SELECT * FROM community_group_invitations WHERE group_id=? AND user_id=? AND status='pending'").get(id,userId);if(!invitation){const invitationId=randomUUID(),time=now();db.prepare('INSERT INTO community_group_invitations(id,group_id,user_id,inviter_id,created_at,updated_at) VALUES(?,?,?,?,?,?)').run(invitationId,id,userId,user.id,time,time);invitation=db.prepare('SELECT * FROM community_group_invitations WHERE id=?').get(invitationId);}return invitationDto(invitation,user.id);});return {items};});return reply(200,result);
    }
    if(action==='leave'&&!target&&req.method==='POST'){await readBody(req,2000);return reply(200,transactionFor(user,()=>{const current=memberRow(id,user.id);if(current.role==='owner')throw new HttpError(409,'群主需要先转让群主或解散群聊。');removeMember(id,user.id);return {ok:true};}));}
    if(action==='transfer'&&!target&&req.method==='POST'){
      manager(id,user.id,true);const body=await readBody(req,2000);if(typeof body.userId!=='string'||body.userId===user.id)throw new HttpError(400,'请选择另一位群成员接任群主。');const result=transactionFor(user,()=>{manager(id,user.id,true);memberRow(id,body.userId);db.prepare("UPDATE community_group_members SET role='member' WHERE group_id=? AND user_id=?").run(id,user.id);db.prepare("UPDATE community_group_members SET role='owner',muted=0 WHERE group_id=? AND user_id=?").run(id,body.userId);db.prepare('UPDATE community_groups SET owner_id=?,updated_at=? WHERE id=?').run(body.userId,now(),id);return {group:groupDto(groupRow(id),user.id)};});return reply(200,result);
    }
    if(action==='messages'&&!target&&req.method==='GET'){
      if(params.has('before')&&params.has('after'))throw new HttpError(400,'不能同时指定 before 和 after。');const limit=limitValue(params,30),forward=params.has('after'),value=params.get(forward?'after':'before'),cursor=value===null?null:messageCursor(value,group,member,user.id,forward),rows=db.prepare(`SELECT * FROM community_group_messages WHERE group_id=? AND seq>? ${cursor===null?'':`AND seq${forward?'>':'<'}?`} ORDER BY seq ${forward?'ASC':'DESC'} LIMIT ?`).all(id,member.joined_seq,...(cursor===null?[]:[cursor]),limit+1),hasMore=rows.length>limit,selected=rows.slice(0,limit),boundary=selected.at(-1);
      if(selected.length)db.prepare('UPDATE community_group_members SET delivered_seq=MAX(delivered_seq,?) WHERE group_id=? AND user_id=? AND id=?').run(Math.max(...selected.map(row=>row.seq)),id,user.id,member.id);
      return reply(200,{items:(forward?selected:[...selected].reverse()).map(row=>messageDto(row,user.id)),hasMore,nextCursor:hasMore?cursorFor(boundary,group,member,user.id):null});
    }
    if(action==='messages'&&!target&&req.method==='POST'){
      const body=await readBody(req,20000),imageIds=attachmentImageIds(body.imageIds),content=text(body.body===undefined?'':body.body,1000,'群消息'),mutation=mutationId(body.clientMutationId),rawMentions=body.mentionUserIds??[];if(!content&&!imageIds.length)throw new HttpError(400,'文字和图片不能同时为空。');if(!Array.isArray(rawMentions)||rawMentions.length>20||rawMentions.some(value=>typeof value!=='string'||!value||value.length>100))throw new HttpError(400,'每条消息最多提醒 20 位群成员。');const mentions=[...new Set(rawMentions)].sort(),mentionAll=body.mentionAll===undefined?false:bool(body.mentionAll,'全体提醒');
      const result=transactionFor(user,()=>{const current=memberRow(id,user.id),currentGroup=groupRow(id),existing=db.prepare('SELECT * FROM community_group_messages WHERE sender_id=? AND client_mutation_id=?').get(user.id,mutation);if(existing){if(existing.group_id!==id||existing.body!==content||existing.mention_all!==Number(mentionAll)||existing.mention_user_ids!==JSON.stringify(mentions)||existing.membership_id!==current.id||existing.seq<=current.joined_seq||JSON.stringify(media?.attachedImageIds('group-message',existing.id)||[])!==JSON.stringify(imageIds))throw new HttpError(409,'此请求唯一键已用于其他群消息或旧入群记录，请保留原请求重试。');return {message:messageDto(existing,user.id)};}if(current.muted||currentGroup.mute_all&&current.role==='member')throw new HttpError(403,'你当前处于禁言状态。');if(mentionAll&&!canManage(current))throw new HttpError(403,'仅群主或管理员可以提醒全体成员。');for(const mentioned of mentions)if(!db.prepare('SELECT 1 FROM community_group_members WHERE group_id=? AND user_id=?').get(id,mentioned))throw new HttpError(400,'只能提醒当前群成员。');throttle(user.id,'group-message-minute',60,60*1000);throttle(user.id,'group-message-hour',1000,60*60*1000);if(imageIds.length&&!media)throw new HttpError(422,'图片附件暂不可用。');const images=media?.verifyForAttachment(user.id,imageIds)||[],messageId=randomUUID(),time=now(),inserted=db.prepare('INSERT INTO community_group_messages(id,group_id,sender_id,membership_id,body,client_mutation_id,mention_user_ids,mention_all,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(messageId,id,user.id,current.id,content,mutation,JSON.stringify(mentions),Number(mentionAll),time);media?.bindAttachment('group-message',messageId,images);db.prepare('UPDATE community_groups SET last_seq=?,updated_at=? WHERE id=?').run(Number(inserted.lastInsertRowid),time,id);return {message:messageDto(db.prepare('SELECT * FROM community_group_messages WHERE id=?').get(messageId),user.id)};});return reply(201,result);
    }
    if(action==='read'&&!target&&req.method==='PUT'){
      const body=await readBody(req,2000);if(typeof body.lastMessageId!=='string'||!body.lastMessageId)throw new HttpError(400,'请指定已收到的最后一条群消息。');const result=transactionFor(user,()=>{const current=memberRow(id,user.id),last=db.prepare('SELECT * FROM community_group_messages WHERE id=? AND group_id=? AND seq>?').get(body.lastMessageId,id,current.joined_seq);if(!last||last.seq>current.delivered_seq)throw new HttpError(400,'只能标记本次入群后已收到的群消息。');if(last.sender_id===user.id)throw new HttpError(400,'只能标记他人发送的群消息为已读。');db.prepare('UPDATE community_group_members SET last_read_seq=MAX(last_read_seq,?) WHERE group_id=? AND user_id=? AND id=?').run(last.seq,id,user.id,current.id);return {...totals(user.id),groupUnreadCount:unreadCount(user.id,id),groupMentionUnreadCount:mentionUnreadCount(user.id,id)};});return reply(200,result);
    }
    throw new HttpError(404,'群聊接口不存在。');
  }
  function exportUser(userId){return {groups:db.prepare("SELECT g.* FROM community_groups g JOIN community_group_members p ON p.group_id=g.id AND p.user_id=? WHERE g.status='active' ORDER BY g.created_at,g.id").all(userId).map(row=>groupDto(row,userId)),messages:db.prepare('SELECT * FROM community_group_messages WHERE sender_id=? ORDER BY seq').all(userId).map(row=>messageDto(row,userId)),invitations:db.prepare('SELECT * FROM community_group_invitations WHERE user_id=? ORDER BY created_at,id').all(userId).map(row=>invitationDto(row,userId)),requests:db.prepare('SELECT * FROM community_group_requests WHERE user_id=? ORDER BY created_at,id').all(userId).map(row=>({groupId:row.group_id,...requestDto(row,userId)}))};}
  function deleteUserData(userId){
    for(const group of db.prepare("SELECT * FROM community_groups WHERE owner_id=? AND status='active'").all(userId)){const successor=db.prepare("SELECT * FROM community_group_members WHERE group_id=? AND user_id<>? ORDER BY CASE role WHEN 'admin' THEN 0 ELSE 1 END,joined_at,user_id LIMIT 1").get(group.id,userId);if(successor){db.prepare("UPDATE community_group_members SET role='member' WHERE group_id=? AND user_id=?").run(group.id,userId);db.prepare("UPDATE community_group_members SET role='owner',muted=0 WHERE group_id=? AND user_id=?").run(group.id,successor.user_id);db.prepare('UPDATE community_groups SET owner_id=?,updated_at=? WHERE id=?').run(successor.user_id,now(),group.id);}else dissolve(group.id);}
    for(const member of db.prepare('SELECT group_id FROM community_group_members WHERE user_id=?').all(userId))removeMember(member.group_id,userId);
    db.prepare('DELETE FROM community_group_messages WHERE sender_id=?').run(userId);db.prepare('DELETE FROM community_group_requests WHERE user_id=?').run(userId);db.prepare('DELETE FROM community_group_invitations WHERE user_id=? OR inviter_id=?').run(userId,userId);db.prepare('DELETE FROM community_group_mutations WHERE user_id=?').run(userId);
  }
  return {handle,unreadCount,exportUser,deleteUserData};
}
